server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-Service
              uri: ${AUTH_SERVICE_URL:lb://AUTH-SERVICE}
              predicates:
                - Path=/auth/**

            - id: cliente
              uri: ${CLIENTE_SERVICE_URL:lb://CLIENTES}
              predicates:
                - Path=/api/clientes/**

            - id: reclamos
              uri: ${RECLAMOS_SERVICE_URL:lb://RECLAMOS}
              predicates:
                - Path=/api/reclamos/**

            - id: productos
              uri: ${PRODUCTOS_SERVICE_URL:lb://PRODUCTOS}
              predicates:
                - Path=/api/productos/**

            - id: servicioTecnico
              uri: ${SERVICIOTECNICO_SERVICE_URL:lb://SERVICIOTECNICO}
              predicates:
                - Path=/api/servicioTecnico/**

            - id: pedidos
              uri: ${PEDIDOS_SERVICE_URL:lb://PEDIDOS}
              predicates:
                - Path=/api/pedidos/**

            - id: devolucion
              uri: ${DEVOLUCION_SERVICE_URL:lb://DEVOLUCION}
              predicates:
                - Path=/api/devoluciones/**

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

jwt:
  secret: laClaveDeLaTiendaDeMusicaEstanLargaLoSuficiente

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: https://danielrangelksh-auth-service.onrender.com/v3/api-docs
      - name: Cliente Service
        url: https://danielrangelksh-cliente.onrender.com/v3/api-docs
      - name: Reclamos Service
        url: https://danielrangelksh-reclamos.onrender.com/v3/api-docs
      - name: Productos Service
        url: https://danielrangelksh-productos.onrender.com/v3/api-docs
      - name: ServicioTecnico Service
        url: https://danielrangelksh-serviciotecnico.onrender.com/v3/api-docs
      - name: Pedidos Service
        url: https://danielrangelksh-pedidos.onrender.com/v3/api-docs
      - name: Devolución Service
        url: https://danielrangelksh-devolucion.onrender.com/v3/api-docs
